Create libraries to handle the server and clients
rooneyshuman/rusty-mancala pull request #1
Opened 2020-02-14 23:52 UTC by rooneyshuman

2020-02-15 17:11 UTC, logyball requested changes
I think we could make the directory structure look like this:

```
- Client/
    - src/
        - lib/
            - library files....
        - main.rs
    - cargo.toml
    - cargo.toml.lock
- Server/
    - src/
        - lib/
            - library files....
        - main.rs
    - cargo.toml
    - cargo.toml.lock
- Protocol/
    - src/
        -library files...
    - cargo.toml
    - cargo.toml.lock
- .git
- readme/etc
```

That way, we could import things something like this: 

In client, import the necessary client modules into `client/src/main.rs` and something similar for server, then import the game protocol as an external crate into both server and clint

2020-02-15 17:11 UTC, logyball commented on mancala/client/src/lib.rs
> +    match TcpStream::connect("localhost:3333") {
can we make the host/port a variable?

2020-02-15 17:11 UTC, logyball commented on mancala/server/src/lib.rs
> +    let listener = TcpListener::bind("0.0.0.0:3333").unwrap();
here as well

2020-02-17 21:03 UTC, rooneyshuman commented
According to rust docs, cargo needs a particular package layout. (https://doc.rust-lang.org/cargo/guide/project-layout.html).
I've updated the layout to the following:
- client/
    - examples/
        - sample_client.rs
    - src/
        - lib.rs
        - main.rs
    - Cargo.toml
    - Cargo.lock
- server/
    - examples/
        - sample_server.rs
    - src/
        - lib.rs
        - main.rs
    - Cargo.toml
    - Cargo.lock
- Protocol/
    - src/
        - main.rs
    - Cargo.toml
    - Cargo.lock
- .git
- readme/etc

2020-02-18 17:33 UTC, logyball approved these changes

2020-02-18 17:33 UTC, loganballard commented on mancala/client/Cargo.toml
> +authors = ["rooneyshuman <rooneyshuman@gmail.com>"]
gonna have to add myself here

2020-02-18 17:33 UTC, loganballard commented on mancala/server/Cargo.toml
> +authors = ["rooneyshuman <rooneyshuman@gmail.com>"]
and here

2020-02-18 17:57 UTC, merged